# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 01:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BobyRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('boby_invited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to='core.Boby')),
                ('boby_inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter', to='core.Boby')),
            ],
        ),
        migrations.AddField(
            model_name='boby',
            name='buddies',
            field=models.ManyToManyField(through='core.BobyRelation', to='core.Boby'),
        ),
        migrations.AddField(
            model_name='boby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
